### ISSUE TITLE
popsicle params

### ISSUE THREAD

**Issue by svnlto** [mulesoft/js-client-oauth2#10]
I'd like to set some of the popsicle options. How'd I go about it?

**Comment by blakeembrey** [comment]
Just curious, what are you trying to do? Should it be something built in? You can provide your own request library by override the `request` property on the `prototype`, seen https://github.com/mulesoft/js-client-oauth2/blob/master/client-oauth2.js#L343-L346.

**Comment by svnlto** [comment]
> Just curious, what are you trying to do?

just want to set `rejectUnauthorized` to false for this thing I'm working on.

> You can provide your own request library by override the request property on the prototype

Thats good to know! So I guess I could just require `popsicle` directly and overwrite the prototype.

**Comment by blakeembrey** [comment]
> just want to set rejectUnauthorized to false for this thing I'm working on.

That seems like a pretty straightforward use-case. Maybe we can define some properties that can be passed through to the request method.

> So I guess I could just require popsicle directly and overwrite the prototype?

Yep, should be as easy as that. Something like:

```js
var auth = new ClientOAuth2()
var popsicle = require('popsicle')
var extend = require('xtend') // You can always assign it directly too.

auth.request = function (opts) {
  return popsicle(extend(opts, { rejectUnauthorized: false }))
}
```

**Comment by svnlto** [comment]
Excellent, thank you.

> Maybe we can define some properties that can be passed through to the request method.

That sounds like a good idea.

**Comment by blakeembrey** [comment]
I just published `0.2.6` with some changes for this. You can now set `rejectUnauthorized` and `agent` options through the constructor.

**Comment by tqm-kmd** [comment]
Is it possible to get an updated example, of how to set rejectUnAuthorized to false? 

(It seems that a lot has changed in the code, since the example in reply number 3 was written)

**Comment by blakeembrey** [comment]
@tqm-kmd The second argument of the constructor can be a custom request function (https://github.com/mulesoft/js-client-oauth2#usage). Combing that with https://github.com/mulesoft/js-client-oauth2/blob/master/src/request/index.js and the solution should be this tiny tweak:

```js
function request (method, url, body, headers) {
  return popsicle.get({
    url: url,
    body: body,
    method: method,
    headers: headers,
    transport: popsicle.createTransport({ rejectUnauthorized: false })
  }).then(function (res) {
    return {
      status: res.status,
      body: res.body
    }
  })
}
```
