### ISSUE TITLE
Using client-oauth2 with typescript

### ISSUE THREAD

**Issue by lgLindstrom** [mulesoft/js-client-oauth2#109]
Hi
I am new to Typescript and having problems using client-oauth2. 
Can anyone give a short example how to login to google using client-oauth2 and typescript ??
( I get error on the first import statement ,, :)  )

This is the error I get 
Module '"..............   node_modules/client-oauth2"' has no exported member 'ClientOauth2'.ts(2305)

**Comment by AnandChowdhary** [comment]
This works perfectly:

```ts
import ClientOAuth2 from "client-oauth2";

const github = new ClientOAuth2({
  clientId: GITHUB_CLIENT_ID,
  clientSecret: GITHUB_CLIENT_SECRET,
  redirectUri: GITHUB_CLIENT_REDIRECT,
  accessTokenUri: "https://github.com/login/oauth/access_token",
  authorizationUri: "https://github.com/login/oauth/authorize",
  scopes: ["user:email"]
});

const getUrl = (url: string) => {
  const url = github.code.getUri();
  return response;
}

const getResponse = async (url: string) => {
  const response = await github.code.getToken(url);
  return response;
}
```

**Comment by postatum** [comment]
Hi @lgLindstrom.

I hope the answer provided above by Anand helped you. If not, feel free to reopen the issue.
