### ISSUE TITLE
Accept "authentication context class reference values (acr_values)" for "Resource Owner Password Credentials Grant"

### ISSUE THREAD

**Issue by EmilioDiRita** [mulesoft/js-client-oauth2#11]
Hi,
In the first place, thank you for your great job.

In my application I need to pass "acr_values" in the request, in order to send more information to the server (in my case the domain for validation).

In the library I modify:
```javascript
OwnerFlow.prototype.getToken = function (username, password) {
    var self = this
    var options = this.client.options

    return this.client._request({
      url: options.accessTokenUri,
      method: 'POST',
      headers: {
        'Accept': 'application/json, application/x-www-form-urlencoded',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': auth(options.clientId, options.clientSecret)
      },
      body: {
        scope: sanitizeScope(options.scopes),
        username: username,
        password: password,
        grant_type: 'password'
      }
    })
      .then(handleAuthResponse)
      .then(function (data) {
        return new ClientOAuth2Token(self.client, data)
      })
  }
```

with this:

```javascript
OwnerFlow.prototype.getToken = function (username, password, acrValues) {
        var self = this
        var options = this.client.options

        return this.client._request({
            url: options.accessTokenUri,
            method: 'POST',
            headers: {
                'Accept': 'application/json, application/x-www-form-urlencoded',
                'Content-Type': 'application/x-www-form-urlencoded',
                'Authorization': auth(options.clientId, options.clientSecret)
            },
            body: {
                scope: sanitizeScope(options.scopes),
                username: username,
                password: password,
                grant_type: 'password',
                acr_values: acrValues
            }
        })
          .then(handleAuthResponse)
          .then(function (data) {
              return new ClientOAuth2Token(self.client, data)
          })
    }
```

I think is not a very big issue and I ask you if is it possible to merge this feature with the library, in order to continue remain sync with it.

Thank you

**Comment by blakeembrey** [comment]
This can't be merged directly since it won't allow us to extend the library in the future. I'm not really sure what `acr_values` is used for too. Do you need it in more locations that just this flow? I think a better solution would be to allow people to pass in `body`/`query`/`headers` objects that can be merged with the generated objects for options. Any objections?

**Comment by EmilioDiRita** [comment]
Thank you very much for your reply.

According to <a href="http://openid.net/specs/openid-connect-core-1_0.html">this</a> document:
<blockquote>acr_values: Requested Authentication Context Class Reference values. Space-separated string that specifies the acr values that the Authorization Server is being requested to use for processing this Authentication Request, with the values appearing in order of preference. The Authentication Context Class satisfied by the authentication performed is returned as the acr Claim Value, as specified in Section 2. The acr Claim is requested as a Voluntary Claim by this parameter.</blockquote>

We need them in order to let our identity server know which login validator use for the request.
So according to your proposal I suggest only this change in the library:
```Javascript
OwnerFlow.prototype.getToken = function (username, password) {
        var self = this
        var options = this.client.options

        var headers = options.headers;
        headers.Accept = 'application/json, application/x-www-form-urlencoded';
        headers.ContentType = 'application/x-www-form-urlencoded';
        headers.Authorization = auth(options.clientId, options.clientSecret);

        var body = options.body;
        body.scope = sanitizeScope(options.scopes);
        body.username = username;
        body.password = password;
        body.grant_type = 'password';

        var query = options.query;

        return this.client._request({
            url: options.accessTokenUri,
            method: 'POST',
            headers: headers,
            body: body
        })
          .then(handleAuthResponse)
          .then(function (data) {
              return new ClientOAuth2Token(self.client, data)
          })
    }
```
and it could be used in a way like this:

```Javascript
var identityServerAuthenticationClient = new ClientOAuth2({
        body:
        {
            accessTokenUri: 'https://localhost/connect/token',
            clientId: 'clientId',
            clientSecret: 'secret',
            scopes: ['scopes'],
            acrValues: acrValues
        }
    });

identityServerAuthenticationClient.owner.getToken(username, password);

```

In this way, in the future, if new options are required, it could be passed without problems or changes in the library.
What do you think? I need to change something else?

Thank you in advance.
