### ISSUE TITLE
Return value of getToken() issue?

### ISSUE THREAD

**Issue by WilliamLehmus** [mulesoft/js-client-oauth2#134]
I can't get my head around the return value of getToken(). The call succeeds and returns a object that isn't really a valid format. From what I've tested this is not a valid JSON object nor a valid JSON string, None of the usual methods such as JSON.parse or JSON.stringify work with the response. 
Is is just me or is this some kind of error in the formatting of the returned data?

If I'm wrong, can somebody please clarify the examples with the correct usage of the
token data. 

This is how the formatting looks on the returned data. 
```
ClientOAuth2Token {
  client:
   ClientOAuth2 {
     options:
      { clientId:
```

**Comment by robbieaverill** [comment]
Hi @WilliamLehmus, `getToken()` returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which resolves and returns a `Token` instance which you can access properties on such as `accessToken`, `data`, etc

**Comment by postatum** [comment]
@robbieaverill answer is correct.
