### ISSUE TITLE
Add additional data to body of refresh token request

### ISSUE THREAD

**Issue by txsl** [mulesoft/js-client-oauth2#14]
A particular OAuth2 provider I'm using requires that the scope be submitted along with the refresh token and grant type (which would be '_refresh_token_' in this case) when refreshing the access token.

I think a neat way to do this might be to pass in an object with any extra parameters which need passing in and extend it with the two parameters (refresh token and grant type).

Happy to write this and submit a PR if you think this is the right approach.

Thanks!

**Comment by blakeembrey** [comment]
Sounds good. I think we can remove the `omit` on the client token data too (seen https://github.com/mulesoft/js-client-oauth2/blob/master/client-oauth2.js#L289). On the body use-case, I'd say let's accept options everywhere and use `options.body` (it's already used globally, let's just enable it at the method level too).

**Comment by txsl** [comment]
I've had a stab at adding options to the refresh method: https://github.com/txsl/js-client-oauth2/commit/da62f94dc576c25bf318a9846f188c0bfbb38392

I don't think it's very clean though - but I can't think of a neater way to sanitise the scope without checking there. Unless it's done in `ClientOAuth2.prototype._requestOptions` - since if scope has already been sanitised it won't do anything.

Re removing `omit` with client data, I'm not sure I follow the aim with that?

**Comment by blakeembrey** [comment]
@txsl Thanks for the attempt, sorry for the long delay. I'll release a new minor version with this enhancement this evening :smile:

**Comment by blakeembrey** [comment]
Released with https://github.com/mulesoft/js-client-oauth2/releases/tag/v2.1.0, you can set `{ body: ... }` with `refresh({ ... })`.
