### ISSUE TITLE
[RFC] Client generates wrong authorization URL if base URL contains query parameters

### ISSUE THREAD

**Issue by jbaron-gingco** [mulesoft/js-client-oauth2#144]
if my authorization URL is something like `https://example.com/foo?bar=qux`, the generated authorization URL is something like `https://example.com/foo?bar=qux?client_id=...`. But [RFC 6749 requires the URL parameters to be kept][1]:

>   The endpoint URI MAY include an "application/x-www-form-urlencoded"
   formatted (per Appendix B) query component ([RFC3986] Section 3.4),
   which MUST be retained when adding additional query parameters.  The
   endpoint URI MUST NOT include a fragment component.

 [1]: https://tools.ietf.org/html/rfc6749#section-3.1

**Comment by postatum** [comment]
Hi @jbaron-gingco.

Thanks for reporting this issue. I've created a PR to fix it.
