### ISSUE TITLE
Invalid calling object 'btoa' in Edge (Chromium)

### ISSUE THREAD

**Issue by agentschmitt** [mulesoft/js-client-oauth2#148]
I have an issue with token.refresh() on edge (chromium edition).
The function throws error "Invalid calling object". The issue seems to come from window.btoa function.
Seems to be related to issue #78 and pr #70.

I tried the fix from the pr and it worked for me.
But i see it has conflicts with master and isnt merged since 2 years.
Can we have this bugfix please? :) I can create new pr if this helps!

**Comment by postatum** [comment]
Hi @agentschmitt.

>  Can we have this bugfix please? :) I can create new pr if this helps!

Please do. I'll review it.

Thanks!

**Comment by agentschmitt** [comment]
@postatum i created the pr with the fix.

**Comment by postatum** [comment]
Closed via https://github.com/mulesoft/js-client-oauth2/pull/150

**Comment by postatum** [comment]
The fix is now released in version 4.3.2. Thank you for the contribution!
