### ISSUE TITLE
Query as string

### ISSUE THREAD

**Issue by Luixo** [mulesoft/js-client-oauth2#16]
I'm trying to send query as string, but `ClientOAuth2.prototype._requestOptions` method malform string to object with chars as keys. 
Is there any way to send string queries without library modification?

**Comment by blakeembrey** [comment]
No, not without library modification. Why do you want to send queries as strings? Is this for the request method or somewhere else? It could be tweaked to support this, but I'd like to understand how you're using it to make sure it works for you first.

**Comment by Luixo** [comment]
I need to send query with repeated keys, so i can't encode it in plain object.

**Comment by blakeembrey** [comment]
An array doesn't work?

**Comment by Luixo** [comment]
Didn't find the description of array shape, but i tried array of object (result: `../?0=&1=&2=..`) and array of strings (result: `../0=string_to_send&1=another_string&2=..`), no luck.

**Comment by blakeembrey** [comment]
Using `{ key: ['one', 'two', ...] }` should work. It's just encoded using `querystring` in the end, and it does repeated keys.

**Comment by Luixo** [comment]
Yep, that works, thank you!
