### ISSUE TITLE
authorization using jwt

### ISSUE THREAD

**Issue by cyrilzaharchenko** [mulesoft/js-client-oauth2#19]
I was trying to implement JWT authorization workflow using this method as described
githubAuth.jwt.getToken('eyJhbGciOiJFUzI1NiJ9.eyJpc3Mi[...omitted for brevity...].J9l-ZhwP[...omitted for brevity...]')
google api responses with an error:
"Parameter not allowed for this message type: client_id"
This error occurs because the library send additional header
Authorization:Basic MTExMzQ3M[...omitted for brevity...]hBNg==

This header is required for other authorization workflow
I wasn't able to create new instance of ClientOAuth2 without specifying client_id.
In the source code 684 row in client-oauth.js

`  if (options.clientId) {
    headers['Authorization'] = auth(options.clientId, options.clientSecret)
  }`

**Comment by blakeembrey** [comment]
@cyrilzaharchenko There is nothing in the code that expects `clientId` to exist, it should be working fine. In fact, the code you point to allows `clientId` to be omitted. If you can't initialise a client without `clientId`, then you can pass in null as an option - `getToken(token, { clientId: null })`.
