### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by pbuyle** [mulesoft/js-client-oauth2#2]
Is there any reason for not providing this library as a Bower package?

**Comment by blakeembrey** [comment]
No reason, we can add it :+1:

**Comment by pbuyle** [comment]
v0.2.0's bower.json does not declare popsicle dependency.

**Comment by blakeembrey** [comment]
@pbuyle You're right, sorry man! All patched now :+1:

**Comment by pbuyle** [comment]
Awesome, thanks.
