### ISSUE TITLE
Token revocation?

### ISSUE THREAD

**Issue by vlavorini** [mulesoft/js-client-oauth2#20]
Hello,

   not really an issue, anyway..

What is the method to ask the server to revoke a token?

Thnak you

**Comment by blakeembrey** [comment]
I don't believe there's anything in the spec on this, so it's not really possible to build against something that may be implemented differently across providers. You can always implement it yourself for a provider.

**Comment by blakeembrey** [comment]
@vlavorini If you ever do run across a standardised way of token revocation, let me know 😄
