### ISSUE TITLE
No support for making calls with multipart forms 

### ISSUE THREAD

**Issue by eazynow** [mulesoft/js-client-oauth2#21]
I've noticed a problem when trying to upload files through an oauth2 authenticated request using this library. The request is not recognised as `multipart/form`.

As the underlying client is popsicle, you should be able to [send a multipart request body](https://github.com/blakeembrey/popsicle#multipart-request-bodies) by creating and passing in a FormData object as the body.

But there are 2 problems with the current app:

**The  popsicle `form` function isn't exposed through the client**
This means an app cannot create the correct `FormData` object. popsicle decides if the body is multipart by [checking if the body is an instanceof FormData](https://github.com/blakeembrey/popsicle/blob/master/lib/plugins/common.ts#L81) and unless the correct FormData is created, it isn't matched.

**requestOptions breaks FormData**
The requestOptions function [does an extend](https://github.com/mulesoft/js-client-oauth2/blob/master/client-oauth2.js#L207) on the body with options which stops it being a FormData instance. It should only extend _if_ options.body is defined.

**Comment by eazynow** [comment]
PR raised with fix for the issue

**Comment by blakeembrey** [comment]
With the recent work for 3.0, I've killed the `request` functionality - it's still very easy to prefer to use `.sign()` instead though.
