### ISSUE TITLE
Azure AD resource ID not provided

### ISSUE THREAD

**Issue by ChrisCooney** [mulesoft/js-client-oauth2#25]
Azure kicks out a missing resource ID error when attempting to use the implicit flow here. Being something of a pain! Has this been tested against Azure AD?

**Comment by blakeembrey** [comment]
No.

**Comment by blakeembrey** [comment]
If you're using the implicit flow, you probably need to add additional parameters to the URL. Can you share some documentation/example of what you're trying to do?

**Comment by blakeembrey** [comment]
This part of the documentation might help you: https://github.com/mulesoft/js-client-oauth2#request-options. You can inject whatever parameter you need on the request you need. This library is generic enough that it should easily adapt to your use-case quickly.

**Comment by jonespen** [comment]
Having a similiar problem, azure ad for some reason expects `response_type` to be `id_token`, not `token`. Since `createUri` extends its own `token` after the passed `options.query` object (https://github.com/mulesoft/js-client-oauth2/blob/master/src/client-oauth2.js#L161-L170), it is not possible (afaik?) to override `response_type`. 

Would it be possible to move the options after the defaults? Something like 
```javascript
  return options.authorizationUri + '?' + Querystring.stringify(extend(
    {
      client_id: options.clientId,
      redirect_uri: options.redirectUri,
      scope: sanitizeScope(options.scopes),
      response_type: tokenType,
      state: options.state
    },
    options.query
  ))
```

**Comment by ChrisCooney** [comment]
After a lot of digging, Azure AD isn't following the exact oAuth2.0 spec. They vary things in subtle ways that only Microsoft can do. I found that writing your own Javascript to make the necessary requests / redirects is the only really easy way of doing it.

**Comment by jonespen** [comment]
Yea, I figured that out to. Guess I'll continue to use adal.js for now, even tho it behaves weird

**Comment by blakeembrey** [comment]
Is that the only change required or is there more? Is there documentation available that I could review? If it's a simple process to support it, I'd love to help.

**Comment by ChrisCooney** [comment]
I'd recommend integrating with Azure OAuth 2.0 (v2.0 of the API); not with V1. V1 is very microsofty. In v2.0 of the application, they've attempted to organise things a little better and follow the oAuth2.0 spec more. If I get some time, I'll write a gist to show how to make successful calls. 

Given I've done this before already, I might submit a pull request myself.

**Comment by jonespen** [comment]
Nice! 👋  if you want some feedback or help
