### ISSUE TITLE
Extra data returned from token endpoint is lost when refreshing

### ISSUE THREAD

**Issue by bontibon** [mulesoft/js-client-oauth2#26]
I am trying to refresh a token at an OpenID Connect endpoint. As per the OpenID specification ([ref](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)), I expend an `id_token` field.

However, `.refresh()` only preserves the `access_token`, `refresh_token`, and `expires_in` fields ([ref](https://github.com/mulesoft/js-client-oauth2/blob/master/client-oauth2.js#L385-L388)).

**Comment by blakeembrey** [comment]
@bontibon `.refresh` is using the same instance, not creating a new instance, so any existing data should still exist.

**Comment by bontibon** [comment]
@blakeembrey Correct. The issue is that the `id_token` field is returned fresh from the token endpoint; it does not exist in the current token instance. When  the `refresh` function is updating `self`, it skips `id_token`.

**Comment by blakeembrey** [comment]
@bontibon So it's only used for refresh endpoints? Perhaps the approach needed is to merged previous with current options, then create a new token instance?

**Comment by bontibon** [comment]
> Perhaps the approach needed is to merged previous with current options, then create a new token instance?

This seems good.
