### ISSUE TITLE
Can't Make Sense of Doc

### ISSUE THREAD

**Issue by omayhemo** [mulesoft/js-client-oauth2#28]
Code Flow Authorization

After I receive the callback, with the code in the body, how am I supposed to get the token?  Your documentation is a bit vague in this area with only the following syntax as explanation.

`githubAuth.code.getToken(req.url)`

Where does the code go?  When I add the code in options I get a weird error unable to process Uri.

**Comment by blakeembrey** [comment]
@omayhemo The authorization code grant is a two step process. It's numbered under https://github.com/mulesoft/js-client-oauth2#authorization-code-grant.  If you've done the redirect and got the URL you landed on, you can then use that URL and give it to `client-oauth2` to be parsed and the next step will occur. Can you share the error you see? It's possible it's not handling the host-less URL.

**Comment by omayhemo** [comment]
I'm already in the callback from the code request of the code flow authorization process by the time client-oauth2 comes into the mix.

This logic occurs in the express route callback from the code request to the provider.  This is specifically SmartThings API.  

At this point I have contacted the 'oauth/token' uri of the provider, popped a modal and logged into the service.  The callback occurs and the modal closes, at that point the server receives the callback from the provider that includes a code in the body, bringing us to this point.




```
var code = req.body.code;
config.oauth2.code.getToken(CALLBACK_URI_HERE, [code]).then((data)=>{
    ... do things ...
}, (data)=>{
	... here I see the error Unable to Process Uri ...
});
```

**Comment by blakeembrey** [comment]
@omayhemo "Unable to process uri" occurs when there's no query string. Can you try using `req. originalUrl` instead?

**Comment by omayhemo** [comment]
I'm confused as to what uri is expected here.  Is it my app redirect url?  Is it the authorization url?
Plus, isn't the qs built through the options parameter of the getToken function?
I'm passing in the code there and the 'client' was fed the remaining qs params when initialized via new ClientOAuth2(options)

It's completely unclear to me.

**Comment by blakeembrey** [comment]
It's the response URI. It'll be parsed, validated and do the next step for you. Did you try the suggestion I made? I don't understand any of the questions you wrote. Authorization is a two-step process, step 1 has no relationship to step 2.

**Comment by omayhemo** [comment]
Clearly we are not on the same page.  Your library supports code flow oauth, correct?

Code Flow Authorization consists of a 3 step process.
1.) Redirect - Redirect to OAuth Provider (eg GitHub)
2.) Accept Callback - Response from Provider on Login Success to predefined URI with Code in Response Body
3.) Request Token - Request Token from Provider using previously received Code

Step 1 and 2 are successfully handled by custom logic.
I have received the callback and I'm holding the code.
I need to request the token using the code.  I have not seen how to do that with your library.  

Your previous suggestion doesn't answer the question at hand.  How and where do I pass the code for the token request?  I don't know if I can articulate any clearer.

**Comment by blakeembrey** [comment]
@omayhemo You don't. You pass me the URL from the callback, as seen in the documentation.

**Comment by blakeembrey** [comment]
The code is fairly simple, here's the `getToken` endpoint. There's no endpoint that only accepts a code, nor anything that hinted that it did accept a code. They all accept the URL and parse it for the code, since there's various edge-cases you may run into parsing the URL yourself. See https://github.com/mulesoft/js-client-oauth2/blob/master/client-oauth2.js#L567-L622 for the implementation.

**Comment by omayhemo** [comment]
OOOOOH

**Comment by blakeembrey** [comment]
That was why I suggested `originalUrl`, because Express is probably stripping the query string from `req.url` here. If it works with `originalUrl`, I'd like to fix that section of the documentation ASAP 😄

**Comment by omayhemo** [comment]
Unfortunately, no that didn't work, which is why I remained confused.  The original url is just the /auth part.  Plus the code is actually in the body, so you wouldn't be able to parse it from there anyway.

**Comment by blakeembrey** [comment]
@omayhemo The code can't be in the body, it's a redirect. So the flow looks like this (if you're using `client-oauth2`).

1. Create an instance of `ClientOAuth2`
2. Get the first URL where you would send the user (it sends them to the application and gives the typical Twitter/Facebook/GitHub/etc. page you'd be used to seeing with the application details). This URL sends you back to the `redirectUri` with a code and other things in the query string.
3. Pass the resulting URL into `getToken` to send the code off and get a more permanent `accessToken`.

You can read the linked section in the specification also - https://tools.ietf.org/html/rfc6749#section-4.1. It's only a redirect, so it can't hold a body.

**Comment by omayhemo** [comment]
Unfortunately first two legs of the process are outside of my control.  The code is most definitely in the body or at least that's how express interprets it.  I'm not smart enough to know why it's that way, all I know is I look at req.body.code to get it out.

**Comment by blakeembrey** [comment]
Can you provide more information about the use-case? How are the first two parts out of your control - if you can tell me? In either case, that shouldn't matter, since the catching the redirect is what matters. Whatever API you're using is not using OAuth 2.0 if they are sending a code in the body - I can check out the API quickly though and verify.

**Comment by omayhemo** [comment]
They are handled at the UI.  This is an integration project with Samsung's SmartThings.
The redirect is sent from Samsung to my service, which is where I catch the code.  They claim it's OAuth 2.0.  This is my first exposure in this stack to this process so I have very little information I can provide.

**Comment by blakeembrey** [comment]
Thanks. I'm taking a look, but I don't have an account to actually test it. I can't see anywhere to sign up either, so guessing it's closed unless I buy something. Reading the documentation, it certainly appears to be using standard OAuth 2.0 - see http://docs.smartthings.com/en/latest/smartapp-web-services-developers-guide/tutorial-part2.html#get-an-access-token.

> When SmartThings redirects back to our application after authorizing, it passes a `code` parameter on the URL.

Do you have some proxying going on in the middle that obscures the direct redirect? Perhaps someone is doing the URL parsing for you and giving you a code?

**Comment by omayhemo** [comment]
It's closed, yes.  You'd have to get an account and create a 'SmartApp Web Service' and then you can get the clientId and clientSecret.

It's totally possible they're snagging it at the UI and sending it to me in the body.  I'll have to inquire.

**Comment by omayhemo** [comment]
So it turns out the front is actually receiving the callback and then calling my service, which is how the code get's into the body.  For that reason, this library isn't suited to my edge case.  Thanks for your help.

**Comment by blakeembrey** [comment]
It's pretty simple to make the changes to support the `code` update. It'd just be pulling out https://github.com/mulesoft/js-client-oauth2/blob/master/src/client-oauth2.js#L620-L639 into its own method. Let me know if you'd like that change.

**Comment by JulianKingman** [comment]
I was also confused by this, thanks for clearing it up :)
(the confusing part is that I retrieved a code and expected to do something with it, and don't use express, so didn't know what originalUrl is)
