### ISSUE TITLE
Default Assumed Config + Paths

### ISSUE THREAD

**Issue by g5codyswartz** [mulesoft/js-client-oauth2#31]
I've seen some very similar libraries in different languages (ruby oauth2 gem) allow for simple assumed end points in its configuration.

It assumes the following endpoints:
oauth/authorize
oauth/token

Here's an example of it's configuration just requiring a clientId, clientSecret, and site URI.
```
OAuth2::Client.new(clientId, clientSecret, :site => site)
```

**Comment by blakeembrey** [comment]
So you'd like to type one URL vs two? I'm probably going to leave it how it is today, as being explicit is really only a one-time cost and makes sense there'll never be any confusion for someone new to the library that it's doing a little magic to pick paths.
