### ISSUE TITLE
transport request options not being passed into the request

### ISSUE THREAD

**Issue by kapiljaveri** [mulesoft/js-client-oauth2#32]
I see that the docs mention a way to pass in the transport object to the popsicle request, but when I try something like:

```
const token = await oauth2.credentials
        .getToken({ transport: { rejectUnauthorized: false }})
        .catch(err => {
          console.log(err);
        });
```

I get SSL errors when using a self-signed cert. In v2.2.0 this used to be by passing in a `options` object, now changed to `transport`, but I do not see that in the [call](https://github.com/mulesoft/js-client-oauth2/blob/master/src/client-oauth2.js#L265) nor in the [request/index.js](https://github.com/mulesoft/js-client-oauth2/blob/master/src/request/index.js#L12) for v3.1.0.

If I'm missing something, do let me know!
Thanks for the lib!

**Comment by blakeembrey** [comment]
Sorry. The docs are outdated, I missed that. You should instead create your own `request` and pass it in with the constructor. See conversation in https://github.com/mulesoft/js-client-oauth2/pull/29, hopefully it's easy enough to wrap your own `request`.

**Comment by kapiljaveri** [comment]
Yepp, got it! No worries. Thanks for the quick reply,
