### ISSUE TITLE
request does not accept the return value from sign

### ISSUE THREAD

**Issue by bontibon** [mulesoft/js-client-oauth2#33]
`ClientOAuth2.request` can be re-worked to accept an object, to work more easily with `.sign`.

Current usage:
```javascript
opts = token.sign({
  method: 'GET',
  url: 'https://example.com/resource'
})
client.request(opts.method, opts.url, opts.body, opts.headers);
```

Proposed usage:

```javascript
client.request(token.sign({
  method: 'GET',
  url: 'https://example.com/resource'
}));
```

**Comment by blakeembrey** [comment]
It's not meant to be used like that. You should probably sign your own request methods where you likely want to do more advanced things like parsing the response, streaming, etc.

**Comment by blakeembrey** [comment]
Definitely let me know if there's something you are trying to do though 😄 The reason that feature from 1.x was killed was to avoid feature/size bloat of the library - instead `request` is used internally and is the absolute minimum allowable size for browsers to function.
