### ISSUE TITLE
Is there a example to use this npm

### ISSUE THREAD

**Issue by yhjhoo** [mulesoft/js-client-oauth2#42]
Is there a example to use this npm

I am getting following error when I am trying implicit flow
`ReferenceError: window is not defined`

**Comment by blakeembrey** [comment]
You shouldn't be using implicit authentication outside of a browser. The code in this library is only sample code to show how it could work, you'd need to make sure that if you're building for a browser that you're popping open a new tab that redirects back and extracts the hash somehow yourself.

**Comment by Mage111** [comment]
But is there any full angular project example , that using these library?
It can be very helpful.
Thanks.
