### ISSUE TITLE
custom response_type

### ISSUE THREAD

**Issue by gitawego** [mulesoft/js-client-oauth2#46]
in my company, the response_type is ``id_token token`` instead of simple ``token``,  could you please make ``response_type`` configurable? I see that it's quite simple to achieve it via method ``createUri ``

something like ``tokenResponseType`` and ``codeResponseType``

thanks in advance

**Comment by blakeembrey** [comment]
This should already be possible today. Pass a `query` object into the flow options (last argument) to override the default configuration. Let me know if you have any issues.

**Comment by blakeembrey** [comment]
Actually, it seems like those particular methods are still merging the opposite direction. Happy to accept a PR to change that: https://github.com/mulesoft/js-client-oauth2/blob/a199dca2f9f59f5de02a6b1b08e3d7404dd7672a/src/client-oauth2.js#L157.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/mulesoft/js-client-oauth2/releases/tag/v4.1.0.
