### ISSUE TITLE
TypeError: Redirected path should match configured path, but got: /pathname/

### ISSUE THREAD

**Issue by azu** [mulesoft/js-client-oauth2#53]
Maybe `redirectUri` check make confuse.

- https://github.com/mulesoft/js-client-oauth2/blob/ac094bc624e3aa169c819759b00f1d3487c3fea2/src/client-oauth2.js#L464-L468

Because, `urlObject.pathname` discriminate between `http://example.com/path` and `http://example.com/path/`, but browser can access both as same page.

Example:

```js
> require("url").parse("https://azu.github.io/irodr")
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'azu.github.io',
  port: null,
  hostname: 'azu.github.io',
  hash: null,
  search: null,
  query: null,
  pathname: '/irodr',
  path: '/irodr',
  href: 'https://azu.github.io/irodr' }
> require("url").parse("https://azu.github.io/irodr/")
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'azu.github.io',
  port: null,
  hostname: 'azu.github.io',
  hash: null,
  search: null,
  query: null,
  pathname: '/irodr/',
  path: '/irodr/',
  href: 'https://azu.github.io/irodr/' }
```

When `redirectUri: "https://azu.github.io/irodr"`, some provider redirect to `https://azu.github.io/irodr/?code=XXX&state=state`. (I know [inoreader.com](http://www.inoreader.com/developers/) does this)
As a result, `"/irodr" === "/irodr/"; // => false` and throw error.

> Redirected path should match configured path, but got: /irodr

Is this expected behavior?

**Comment by blakeembrey** [comment]
> but browser can access both as same page.

This would depend on your server configuration. Not all configurations will respond the same with a trailing slash as without.

In your case I believe it's caused by GitHub pages redirecting you to add the trailing slash, since it would be against spec for the service to redirect you somewhere else. Can you verify this? After that, you can set your redirect URI to with a slash instead to fix the error.

**Comment by azu** [comment]
> In your case I believe it's caused by GitHub pages redirecting you to add the trailing slash, since it would be against spec for the service to redirect you somewhere else. Can you verify this?

Yes. Adding `/` is ok.



Thanks.
