### ISSUE TITLE
Object.assign(...) and Promise(...)

### ISSUE THREAD

**Issue by zameb** [mulesoft/js-client-oauth2#54]
Object.assign(...) is not adopted by all major browsers yet (specially IE, you know)
"Not supported in the following document modes: Quirks, ... Internet Explorer 10 standards, Internet Explorer 11 standards. Not supported in Windows 8.1"
https://docs.microsoft.com/en-us/scripting/javascript/reference/object-assign-function-object-javascript
When I put a polyfill, I discover the next error with Promise().

Some customers still use old versions and when it is about security (OAuth2 is), they have to pay $$$$$ in certifications and audits to update all their technology stack. So, is not on me to say "update your browser" even when I could give good reasons.
I would not suggest to downgrade this awesome work, but do you know of any workaround for all of these problems?
Thanks

**Comment by blakeembrey** [comment]
It's in the README: https://github.com/mulesoft/js-client-oauth2#dependencies. You'll need to polyfill these two features.

**Comment by zameb** [comment]
Thanks blakeembrey, 
I finally could solve by following this guidelines for babel-polyfill: https://babeljs.io/docs/usage/polyfill/
In my case, it allowed me to support IE10 and beyond
