### ISSUE TITLE
npm installing failing

### ISSUE THREAD

**Issue by pkcheruvu** [mulesoft/js-client-oauth2#62]
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "client-oauth2" "--save"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "client-oauth2" under a package
npm ERR! also called "client-oauth2". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by evert** [comment]
This sounds somewhat clear to me. You have a `package.json` that has the name `client-oauth2`, and npm is preventing you from installing a dependency with the same name. Rename your package in the top-level package.json.

**Comment by jstoiko** [comment]
thanks @evert. closing.
