### ISSUE TITLE
Can this library be used with plain javascript SPA? 

### ISSUE THREAD

**Issue by mrshawn191** [mulesoft/js-client-oauth2#63]
Can this library be used with plain javascript SPA?  Or is it node.js only?

**Comment by NLincoln** [comment]
https://github.com/mulesoft/js-client-oauth2#usage

> The module supports executing all the various OAuth 2.0 flows in **any JavaScript environment**

It works in both browsers and node.

**Comment by jstoiko** [comment]
Thanks @NLincoln
