### ISSUE TITLE
Popsicle does not load when AMD loader is used

### ISSUE THREAD

**Issue by pbuyle** [mulesoft/js-client-oauth2#7]
When loaded using an AMD loader, `ClientOAuth2.prototype.request` is `undefined`.

Popsicle itslef works when loaded as an AMD module.

Popsicle is resolved using `var popsicle = hasRequire ? require('popsicle') : root.popsicle`, using the global `require()` if available. A global `require()` is not required for an AMD implementation (see https://github.com/amdjs/amdjs-api/blob/master/require.md). RequireJS for instance does not provide a global `require()`.

A quick woraround is to rewtite the AMD loading code like this:
```javascript
define(['popsicle'], function (popsicle) {
  ClientOAuth2.prototype.request = popsicle;
  return ClientOAuth2
})
```

But I'm not sure this would be the proper fix. I don't have any experience writing multi-loaders library and don't known about the recommended patterns to do it.

**Comment by blakeembrey** [comment]
You're right, this is a massive PITA and I should get some more experience. I thought requireJS did implement a parser for the `require('')` syntax though. Anyway, let me work it out. Thanks for all the issues and PRs you've been helping with!

**Comment by blakeembrey** [comment]
@pbuyle Yet another version :+1: It should work now :smile:

**Comment by pbuyle** [comment]
Thanks :smile:
