### ISSUE TITLE
Invalid calling object 'btoa' in IE11

### ISSUE THREAD

**Issue by kyemelianov** [mulesoft/js-client-oauth2#78]
We an issue in IE11 after build product version.
It is described and resolved in [PR70](https://github.com/mulesoft/js-client-oauth2/pull/70)
IE11 can't use 'btoa' without window context.
It is easy reproduce in IE11:
({ btoa: window.btoa }).btoa('123') - return Error

**Comment by postatum** [comment]
Closed via https://github.com/mulesoft/js-client-oauth2/pull/150

**Comment by postatum** [comment]
The fix is now released in version 4.3.2. Thank you for the report!
